### ISSUE TITLE
"Hardware revision is not supported"

### ISSUE THREAD

**Issue by kayatf** [Drumber/RemoteLightServer#2]
Hey, I always get an error when trying to connect the client to the server. I tried several different versions and executing it with and without sudo.

I'm btw. running OpenJDK 1.8.0_212 under Raspbian 10.
My leds are WS2811

```root@raspberrypi:/home/pi/server# java -jar RemoteLightServer-pre0.2.0.1.jar
<=== RemoteLightServer pre-0.2.0.1 by Lars O. ===>
>> Type 'end' or 'CTRL + C' to exit...
[13:20:21] [INFO] [Server] Wating for connection...
[13:20:24] [INFO] [Server] Client connected: /192.168.8.139:52786
Loaded library 'ws281xj' from classpath
ws2811_init failed: Hardware revision is not supported
[13:20:24] [ERROR] java.lang.RuntimeException: Error initialising the WS281x strip
        at com.diozero.ws281xj.rpiws281x.WS281x.<init>(WS281x.java:172)
        at com.diozero.ws281xj.rpiws281x.WS281x.<init>(WS281x.java:139)
        at de.lars.remotelightserver.PixelController.<init>(PixelController.java:15)
        at de.lars.remotelightserver.Main.createPixelController(Main.java:64)
        at de.lars.remotelightserver.server.Server$1.run(Server.java:70)
        at java.lang.Thread.run(Thread.java:748)```

**Comment by Drumber** [comment]
Hi, I saw that you are using version pre0.2.0.1.
Please try the latest RemoteLightServer version (pre0.2.0.3). You can download it here: https://github.com/Drumber/RemoteLightServer/releases/tag/pre0.2.0.3

If the error still occurs, it could be due to the support of the Raspberry Pi model you are using. 
In this case please write me which Raspberry Pi you are using.

**Comment by kayatf** [comment]
Nah, I already tried the latest vesion before but I wanted to try a version that matches up with the client/server.

 

I’m using a pi 4 so I’m pretty much concerned it wasn’t yet tested on it.

 

Von: Lars <notifications@github.com> 
Gesendet: Donnerstag, 23. April 2020 14:34
An: Drumber/RemoteLightServer <RemoteLightServer@noreply.github.com>
Cc: Danii Riegler <daniel.riegler@nms-gruenburg.at>; Author <author@noreply.github.com>
Betreff: Re: [Drumber/RemoteLightServer] "Hardware revision is not supported" (#2)

 

Hi, I saw that you are using version pre0.2.0.1.
Please try the latest RemoteLightServer version (pre0.2.0.3). You can download it here: https://github.com/Drumber/RemoteLightServer/releases/tag/pre0.2.0.3

If the error still occurs, it could be due to the support of the Raspberry Pi model you are using.
In this case please write me which Raspberry Pi you are using.

**Comment by Drumber** [comment]
Ah, that might be the problem. I'll try to add support for Raspberry Pi 4.
I'll let you know as soon as I have an update.

**Comment by kayatf** [comment]
Okey, thank you for your quick response!

 

Von: Lars <notifications@github.com> 
Gesendet: Donnerstag, 23. April 2020 14:43
An: Drumber/RemoteLightServer <RemoteLightServer@noreply.github.com>
Cc: Danii Riegler <daniel.riegler@nms-gruenburg.at>; Author <author@noreply.github.com>
Betreff: Re: [Drumber/RemoteLightServer] "Hardware revision is not supported" (#2)

 

Ah, that might be the problem. I'll try to add support for Raspberry Pi 4.
I'll let you know as soon as I have an update.

**Comment by Drumber** [comment]
Hey, I updated to the latest snapshot of the diozero library. The version should now be compatible with Raspberry Pi 4 boards up to revision 1.1.
Maybe you could test the new version before I release it and tell me if it works.

[RemoteLightServer-pre0.2.0.4-SNAPSHOT.jar.zip](https://github.com/Drumber/RemoteLightServer/files/4522767/RemoteLightServer-pre0.2.0.4-SNAPSHOT.jar.zip)

**Comment by kayatf** [comment]
Yeah, Im gonna try it. I’ll hit you up.

 

Von: Lars <notifications@github.com> 
Gesendet: Donnerstag, 23. April 2020 15:37
An: Drumber/RemoteLightServer <RemoteLightServer@noreply.github.com>
Cc: Danii Riegler <daniel.riegler@nms-gruenburg.at>; Author <author@noreply.github.com>
Betreff: Re: [Drumber/RemoteLightServer] "Hardware revision is not supported" (#2)

 

Hey, I updated to the latest snapshot of the diozero library. The version should now be compatible with Raspberry Pi 4 boards up to revision 1.1.
Maybe you could test the new version before I release it and tell me if it works.

RemoteLightServer-pre0.2.0.4-SNAPSHOT.jar.zip <https://github.com/Drumber/RemoteLightServer/files/4522767/RemoteLightServer-pre0.2.0.4-SNAPSHOT.jar.zip>

**Comment by kayatf** [comment]
It works now. Flawlessy as I can tell. Thanks for your blazingly fast support. Keep on the good work!

 

Von: Lars <notifications@github.com> 
Gesendet: Donnerstag, 23. April 2020 15:37
An: Drumber/RemoteLightServer <RemoteLightServer@noreply.github.com>
Cc: Danii Riegler <daniel.riegler@nms-gruenburg.at>; Author <author@noreply.github.com>
Betreff: Re: [Drumber/RemoteLightServer] "Hardware revision is not supported" (#2)

 

Hey, I updated to the latest snapshot of the diozero library. The version should now be compatible with Raspberry Pi 4 boards up to revision 1.1.
Maybe you could test the new version before I release it and tell me if it works.

RemoteLightServer-pre0.2.0.4-SNAPSHOT.jar.zip <https://github.com/Drumber/RemoteLightServer/files/4522767/RemoteLightServer-pre0.2.0.4-SNAPSHOT.jar.zip>

**Comment by Drumber** [comment]
That's good. I am thus closing this issue. If anything else comes up, just let me know.
