### ISSUE TITLE
Server protocol clarification

### ISSUE THREAD

**Issue by piccinnigius** [Drumber/RemoteLightServer#3]
Awesome work! only one question, wich is the server protocol of json?
i've tried to send the json array over 20002 port but i've got only errors in decoding...

Thanks so much!

**Comment by Drumber** [comment]
Hey, the protocol consists of a Json array, which contains as many Json objects as the set number of pixels.
A Json object contains the RGB color ("value") represented as 4 bytes integer and the alpha value ("falpha"), which is actually always 0.0.

Example packet (2 pixels):
`[{"value":-65536,"falpha":0.0},{"value":-65536,"falpha":0.0}]`

### `value` parameter
value '-65536' converted to binary (2's complement):
`11111111 11111111 00000000 00000000` == red
- bits 0-7 (first byte) represents the **blue** value
- bits 8-15 (second byte) represents the **green** value
- bits 16-23 (third byte) represents the **red** value
- last 8 bits (fourth byte) are all set to 1

`11111111 00000000 00000000 00000000` would be black

### `falpha` parameter
- float value
- not used

Here are the relevant lines in the code:
- [serialize to json](https://github.com/Drumber/RemoteLight/blob/f25326a231be9a8c51060088e5fd744a8807a7c4/remotelight-core/src/main/java/de/lars/remotelightcore/devices/remotelightserver/RLClient.java#L130)
- [custom color class](https://github.com/Drumber/RemoteLight/blob/f25326a231be9a8c51060088e5fd744a8807a7c4/remotelight-core/src/main/java/de/lars/remotelightcore/utils/color/Color.java#L105)

However, I had planned to rework and optimize the protocol (only send colors as bytes and not serialized as json). As soon as the new protocol is ready, I would post it here.

**Comment by piccinnigius** [comment]
Hi @Drumber sorry for late feedback.   I would like to reach a point where the server can be called throght websocket or some generic js apis! As soon as I can make a test i and I will keep you updated under this issue
